### ISSUE TITLE
Enable X410 at startup needs a confirmation

### ISSUE THREAD

**Issue by crramirez** [WhitewaterFoundry/pengwin-setup#229]
It is by design in pengwin-setup that everything has a confirmation. So the user expects that after select X410 in the menu they receive a confirmation asking if they want to enable X410 at startup

@branchard

**Comment by crramirez** [comment]
@branchard

**Comment by branchard** [comment]
I'll fix this as soon as I get some free time.

**Comment by crramirez** [comment]
Thanks a lot. I had to make some adjustments but in general work great. With it, this functionality will be ready

**Comment by crramirez** [comment]
Fixed
