### ISSUE TITLE
mount: /proc: proc already mounted on /proc at login

### ISSUE THREAD

**Issue by w495** [WhitewaterFoundry/pengwin-setup#308]
It happens in ` /etc/profile.d/mount-proc.sh`  with call `sudo /usr/bin/mount-proc`.

Cmd ⇨ Microsoft Windows Version 10.0.18363.1256
Control Pane ⇨ Windows 10 Pro 1909.

Instead of 
```bash
if ( which cmd.exe >/dev/null ); then
```
I suggest to do that:
```bash
 if [[ "$(df /proc | grep proc)x" == "x" ]];  then
```

**Comment by crramirez** [comment]
Hello,

One question did you install Cassandra from pengwin-setup? If the answer is yes. Do you use it?

Regards

**Comment by saigkill** [comment]
Now the syntax error is gone. I tested it on my system. Now it mounts /proc just if it isn't mounted already.
