### ISSUE TITLE
Prompt handling in pengwin-setup install

### ISSUE THREAD

**Issue by Smithienious** [WhitewaterFoundry/pengwin-setup#331]
I am writing a bootstrap script that uses pengwin-setup. There are many packages with yes/no prompt like GUI SYNAPTIC.

```
pengwin-setup install GUI SYNAPTIC
```

Appending YES does not do anything. Is there any workaround or this will need implementation?

As a side note, I think we need documents on using pengwin-setup as a script.

**Comment by crramirez** [comment]
Hello,

Using pengwin-setup as a script is not complete yet. Please put here the list of installers that you need to add to your script and are showing yes/no prompts.

About documentation, yes it is needed and a high requested feature. We don't have a date for this yet sadly.

Regards,
Carlos

**Comment by Smithienious** [comment]
Hello,

I just ran through my scripts and here are the problematic installers

```
GUI SYNAPTIC
```
There is no need for prompts here as I already chose to install this

```
SETTINGS SHELLS ZSH
```
I expect a prompt like https://github.com/WhitewaterFoundry/Pengwin/issues/667

Regards.

**Comment by crramirez** [comment]
Hello @Smithienious ,

We implemented this some time ago but I didn't update this issue.

Test it if you can

Regards,
Carlos
