### ISSUE TITLE
Bump pyenv python installation version to 3.9.2

### ISSUE THREAD

**Issue by Smithienious** [WhitewaterFoundry/pengwin-setup#332]
https://github.com/WhitewaterFoundry/pengwin-setup/blob/6b96876cc24ecdfc38b895dc0a03cc2c71ce0c73/pengwin-setup.d/pythonpi.sh#L43

https://github.com/WhitewaterFoundry/pengwin-setup/blob/6b96876cc24ecdfc38b895dc0a03cc2c71ce0c73/pengwin-setup.d/pythonpi.sh#L44

**Comment by Smithienious** [comment]
I proposed the changes here https://github.com/WhitewaterFoundry/pengwin-setup/pull/333

**Comment by crramirez** [comment]
Hello,

Thanks for the contributions. But why did you close them? 

Regards

**Comment by Smithienious** [comment]
Hello,

I had concerns while making a request to the master branch. While making the dotfiles, I found some installers with newer version. Maybe I will bump all of them to the master branch if it's not that big of a problem.

Regards.
