### ISSUE TITLE
XRDP login fails after install sdkman via pengwin-setup

### ISSUE THREAD

**Issue by bierbo** [WhitewaterFoundry/pengwin-setup#359]
I have installed xfce4 and xrdp in pengwin right after the first apt update && apt upgrade via
`sudo apt install xfce4 xrdp`
This worked immediately out of the box.
After that, I wanted to add several things via pengwin-setup:

- code
- dotnet
- jetbrains
- rc.local
- java (sdkman)

At first, I have installed everything, then I realized, that xrdp just closes the connection after I try to login via Remote Desktop Client.
My second attempt was to install every point in pengwin-setup separately and after every point make a login attempt via RDP.
After installing of sdkman, login failed.

I have also uninstalled pengwin and installed it again via store to ensure that I am using the latest version.

**Comment by crramirez** [comment]
Hello @bierbo ,

Thank you for the detailed report. We will reproduce the error and submit a patch.

Regards,
Carlos

**Comment by crramirez** [comment]
Hello @bierbo ,

We released an update to pengwin-setup. Please run it again to install Java, it will correctly install the fix. The downside is that you won't be able to use sdkman into the RDP session, unless you manually call: `. "${HOME}/.sdkman/bin/sdkman-init.sh` inside the RDP session.

Regards,
Carlos
