### ISSUE TITLE
Why should mozc be checked by default for the installation of ibus?

### ISSUE THREAD

**Issue by linghengqian** [WhitewaterFoundry/pengwin-setup#378]
- I noticed https://github.com/WhitewaterFoundry/pengwin-setup/blob/master/pengwin-setup.d/ibus.sh , `mozc` is checked by default for the installation of ibus. Why? I don't see the relevant reasons in the ibus document.
- ![image](https://user-images.githubusercontent.com/20187731/201462538-db5b9ad5-b88b-43a2-933a-b06c99a9daef.png)

**Comment by crramirez** [comment]
Hello @linghengqian,

Probably a mistake in the testing environment that went through production, and until now, nobody said anything about it.

It was corrected here: https://github.com/WhitewaterFoundry/pengwin-setup/commit/f8903b97765b87520f6f5c0b4a64329d3f34e6b7 and will be included in the next release.

Thank you for reporting

**Comment by linghengqian** [comment]
- Thanks, I will close this issue.
